# Branches that trigger a build on commit
trigger:
- master
- master-vs-deps
- release/*
- features/*
- demos/*

# Branches that trigger builds on PR
pr:
- master
- master-vs-deps
- release/*
- features/*
- demos/*

jobs:
- task: RichCodeNavIndexer@0
  inputs:
    languages: 'csharp'
    githubServiceConnection: 'noellelc'
    environment: 'production'